import {Plus} from 'lucide-react'
import {useEffect,useState} from 'react'
import {useNavigate,useSearchParams} from 'react-router-dom'
import {Artwork} from '../components/Artwork';import {ListControls} from '../components/ListControls';import {TrackRow} from '../components/TrackRow'
import {api} from '../lib/api';import {useListView,type ListSort} from '../lib/useListView';import {usePlayer} from '../lib/player'
import type {Album,Artist,Playlist,RadioStation,Song} from '../types'
type Tab='songs'|'albums'|'artists'|'playlists'|'radio';const alpha=(a:string,b:string)=>a.localeCompare(b,undefined,{sensitivity:'base'})
const songSorts:ListSort<Song>[]=[{value:'title',label:'Title',compare:(a,b)=>alpha(a.title,b.title)},{value:'artist',label:'Artist',compare:(a,b)=>alpha(a.artist,b.artist)},{value:'album',label:'Album',compare:(a,b)=>alpha(a.album,b.album)},{value:'duration',label:'Time',compare:(a,b)=>a.duration_ms-b.duration_ms}]
const albumSorts:ListSort<Album>[]=[{value:'title',label:'Title',compare:(a,b)=>alpha(a.title,b.title)},{value:'artist',label:'Artist',compare:(a,b)=>alpha(a.artist,b.artist)},{value:'year',label:'Year',compare:(a,b)=>a.year-b.year},{value:'songs',label:'Song count',compare:(a,b)=>a.song_count-b.song_count}]
const artistSorts:ListSort<Artist>[]=[{value:'name',label:'Name',compare:(a,b)=>alpha(a.name,b.name)},{value:'albums',label:'Albums',compare:(a,b)=>a.album_count-b.album_count},{value:'songs',label:'Songs',compare:(a,b)=>a.song_count-b.song_count}]
const playlistSorts:ListSort<Playlist>[]=[{value:'name',label:'Name',compare:(a,b)=>alpha(a.name,b.name)},{value:'songs',label:'Songs',compare:(a,b)=>a.song_count-b.song_count},{value:'updated',label:'Updated',compare:(a,b)=>alpha(a.updated_at,b.updated_at)}]
const radioSorts:ListSort<RadioStation>[]=[{value:'name',label:'Name',compare:(a,b)=>alpha(a.name,b.name)},{value:'genre',label:'Genre',compare:(a,b)=>alpha(a.genre,b.genre)},{value:'market',label:'Market',compare:(a,b)=>alpha(a.market,b.market)},{value:'type',label:'Type',compare:(a,b)=>alpha(a.station_type,b.station_type)},{value:'format',label:'Format',compare:(a,b)=>alpha(a.format,b.format)}]
export function LibraryPage(){
 const [sp,setSP]=useSearchParams(),initial=(sp.get('tab') as Tab)||'albums',[tab,setTab]=useState<Tab>(initial),[songs,setSongs]=useState<Song[]>([]),[albums,setAlbums]=useState<Album[]>([]),[artists,setArtists]=useState<Artist[]>([]),[playlists,setPlaylists]=useState<Playlist[]>([]),[radio,setRadio]=useState<RadioStation[]>([]),[radioMarket,setRadioMarket]=useState(''),[radioType,setRadioType]=useState(''),[radioGenre,setRadioGenre]=useState(''),nav=useNavigate(),player=usePlayer()
 useEffect(()=>{void Promise.all([api.songs(),api.albums(),api.artists(),api.playlists(),api.radio()]).then(([s,a,ar,p,r])=>{setSongs(s);setAlbums(a);setArtists(ar);setPlaylists(p);setRadio(r)})},[])
 const filteredRadio=radio.filter(r=>(!radioMarket||r.market===radioMarket)&&(!radioType||r.station_type===radioType)&&(!radioGenre||r.genre===radioGenre)),sv=useListView(songs,s=>`${s.title} ${s.artist} ${s.album}`,songSorts),av=useListView(albums,a=>`${a.title} ${a.artist} ${a.year}`,albumSorts),arv=useListView(artists,a=>a.name,artistSorts),pv=useListView(playlists,p=>p.name,playlistSorts),rv=useListView(filteredRadio,r=>`${r.name} ${r.call_sign} ${r.frequency} ${r.genre} ${r.format} ${r.station_type} ${r.city} ${r.region} ${r.market} ${r.description}`,radioSorts)
 const choose=(t:Tab)=>{setTab(t);setSP({tab:t},{replace:true})}
 return <div className="page"><header className="simple-header"><h1>Library</h1>{tab==='playlists'&&<a className="icon-button glass" href="/admin/playlists" aria-label="Create a playlist in Admin" title="Create a playlist in Admin"><Plus/></a>}</header><div className="tabs-scroll">{(['songs','albums','artists','playlists','radio'] as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>choose(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 {tab==='songs'&&<><ListControls view={sv} sorts={songSorts} label="songs"/><div className="track-stack library-list">{sv.visible.map(s=><TrackRow key={s.id} song={s}/>)}</div></>}
 {tab==='albums'&&<><ListControls view={av} sorts={albumSorts} label="albums"/><div className="album-grid library-grid">{av.visible.map(a=><button className="album-tile" key={a.id} onClick={()=>nav(`/album/${a.id}`)}><Artwork artwork={a.artwork} label={a.title} className="album-art"/><strong>{a.title}</strong><small>{a.artist} · {a.year}</small></button>)}</div></>}
 {tab==='artists'&&<><ListControls view={arv} sorts={artistSorts} label="artists"/><div className="entity-list library-list">{arv.visible.map(a=><button key={a.id} onClick={()=>nav(`/artist/${a.id}`)}><Artwork artwork={a.artwork} label={a.name} className="entity-art circle"/><span><strong>{a.name}</strong><small>{a.album_count} albums · {a.song_count} songs</small></span></button>)}</div></>}
 {tab==='playlists'&&<><ListControls view={pv} sorts={playlistSorts} label="playlists"/><div className="entity-list library-list">{pv.visible.map(p=><button key={p.id} onClick={()=>nav(`/playlist/${p.id}`)}><Artwork artwork={p.artwork} label={p.name} className="entity-art"/><span><strong>{p.name}</strong><small>{p.song_count} songs</small></span></button>)}</div></>}
 {tab==='radio'&&<><div className="radio-directory-filters"><select aria-label="Radio market" value={radioMarket} onChange={e=>setRadioMarket(e.target.value)}><option value="">All markets</option>{[...new Set(radio.map(r=>r.market).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select><select aria-label="Radio type" value={radioType} onChange={e=>setRadioType(e.target.value)}><option value="">All types</option>{[...new Set(radio.map(r=>r.station_type).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select><select aria-label="Radio genre" value={radioGenre} onChange={e=>setRadioGenre(e.target.value)}><option value="">All genres</option>{[...new Set(radio.map(r=>r.genre).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select></div><ListControls view={rv} sorts={radioSorts} label="stations"/><div className="radio-grid library-list">{rv.visible.map(r=><button className="radio-card" key={r.id} onClick={()=>void player.playRadio(r.id)}><Artwork artwork={r.artwork} label={r.name} className="radio-art"/><span className="live-pill">LIVE</span><strong>{r.name}</strong><small>{[r.city&&`${r.city}, ${r.region}`,r.format||r.genre].filter(Boolean).join(' · ')}</small></button>)}</div></>}</div>
}
