import { ChevronDown, Disc3, Heart, ListMusic, Lock, MoreHorizontal, Pause, Play, Plus, Radio, Repeat, Repeat1, Shuffle, SkipBack, SkipForward, Square, Unlock, UserRound, Volume2, VolumeX } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Artwork } from '../components/Artwork'
import { duration } from '../lib/format'
import { usePlayer } from '../lib/player'
export function NowPlayingPage(){const p=usePlayer(),state=p.player,nav=useNavigate(),[position,setPosition]=useState(state?.position_ms||0),[locked,setLocked]=useState(false),[actionsOpen,setActionsOpen]=useState(false);useEffect(()=>setPosition(state?.position_ms||0),[state?.position_ms,state?.track_id]);useEffect(()=>{if(state?.status!=='playing')return;const id=setInterval(()=>setPosition(x=>Math.min(state.duration_ms||x+1000,x+1000)),1000);return()=>clearInterval(id)},[state?.status,state?.duration_ms]);useEffect(()=>{if(!actionsOpen)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setActionsOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[actionsOpen]);if(!state)return <div className="page loading">Connecting…</div>;const song=state.current_song,radio=state.current_radio,title=song?.title||radio?.name||'Nothing playing',artist=song?.artist||radio?.genre||'Music Room',art=song?.artwork||radio?.artwork,close=()=>setActionsOpen(false);return <div className={`now-page ${locked?'locked':''}`}>
  <header className="now-header"><button className="icon-button" aria-label="Close now playing" onClick={()=>nav(-1)}><ChevronDown/></button><div><span>{radio?'LIVE RADIO':'NOW PLAYING'}</span><strong>Music Room</strong></div><button className="icon-button" aria-label="More playback actions" aria-haspopup="dialog" aria-expanded={actionsOpen} onClick={()=>setActionsOpen(true)}><MoreHorizontal/></button></header>
  <div className="now-stage"><Artwork artwork={art} label={title} className="now-art"/><div className="now-copy"><div><h1>{title}</h1><p>{artist}{song&&<span> · {song.album}</span>}</p></div>{song&&<button className="icon-button" aria-label={song.favorite?'Remove from favorites':'Add to favorites'} onClick={()=>void p.favorite(song)}><Heart fill={song.favorite?'currentColor':'none'}/></button>}</div>
  {!radio&&<div className="progress-wrap"><input aria-label="Playback position" type="range" min="0" max={state.duration_ms||1} value={Math.min(position,state.duration_ms||1)} onChange={e=>setPosition(Number(e.target.value))} onPointerUp={()=>void p.seek(position)}/><div><span>{duration(position)}</span><span>-{duration(Math.max(0,state.duration_ms-position))}</span></div></div>}
  <div className="transport"><button aria-label={state.shuffle?'Turn shuffle off':'Turn shuffle on'} aria-pressed={state.shuffle} className={state.shuffle?'active':''} onClick={()=>void p.shuffle()}><Shuffle/></button><button aria-label="Previous track" onClick={()=>void p.previous()}><SkipBack/></button><button aria-label={state.status==='playing'?'Pause':'Play'} className="play-button" onClick={()=>void p.toggle()}>{state.status==='playing'?<Pause/>:<Play/>}</button><button aria-label="Next track" onClick={()=>void p.next()}><SkipForward/></button><button aria-label={`Repeat: ${state.repeat}`} className={state.repeat!=='off'?'active':''} onClick={()=>void p.repeat()}>{state.repeat==='track'?<Repeat1/>:<Repeat/>}</button></div>
  <div className="volume-control">{state.volume===0?<VolumeX/>:<Volume2/>}<input aria-label="Volume" type="range" min="0" max="85" value={state.volume} onChange={e=>void p.volume(Number(e.target.value))}/><span>{state.volume}</span></div>
  <div className="now-bottom"><button aria-label="Open playback queue" onClick={()=>nav('/queue')}><ListMusic/><span><small>UP NEXT</small><strong>{p.queue[state.queue_index+1]?.song.title||'End of queue'}</strong></span><b>{p.queue.length}</b></button><button className="lock-button" onClick={()=>setLocked(true)}><Lock/>Lock controls</button></div></div>
  {locked&&<div className="locked-overlay"><Artwork artwork={art} label={title} className="locked-art"/><h2>{title}</h2><span>{artist}</span><button onClick={()=>setLocked(false)}><Unlock/> Unlock controls</button></div>}
  {actionsOpen&&<div className="sheet-backdrop" onClick={close}><div className="action-sheet" role="dialog" aria-modal="true" aria-label="Playback actions" onClick={e=>e.stopPropagation()}><div className="sheet-grabber"/><div className="sheet-song"><Artwork artwork={art} label={title} className="track-art"/><div><strong>{title}</strong><span>{artist}</span></div></div>{song&&<><button onClick={()=>{void p.play(song.id);close()}}><Play/>Play from beginning</button><button onClick={()=>{void p.addQueue(song.id);close()}}><Plus/>Add to queue</button>{song.artist_id>0&&<button onClick={()=>{nav(`/artist/${song.artist_id}`);close()}}><UserRound/>View artist</button>}{song.album_id>0&&<button onClick={()=>{nav(`/album/${song.album_id}`);close()}}><Disc3/>View album</button>}</>}{radio&&<button onClick={()=>{nav('/library?tab=radio');close()}}><Radio/>Browse radio stations</button>}<button onClick={()=>{void p.stop();close()}}><Square/>Stop playback</button><button onClick={()=>{nav('/queue');close()}}><ListMusic/>View queue</button><button className="sheet-cancel" onClick={close}>Cancel</button></div></div>}
</div>}
