ALTER TABLE songs ADD COLUMN track_number INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN disc_number INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN codec TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN bitrate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN sample_rate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN channels INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN file_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN original_filename TEXT NOT NULL DEFAULT '';
ALTER TABLE songs ADD COLUMN imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS idx_songs_sha256 ON songs(sha256) WHERE sha256 <> '';

ALTER TABLE import_jobs ADD COLUMN source_path TEXT NOT NULL DEFAULT '';
ALTER TABLE import_jobs ADD COLUMN song_id INTEGER REFERENCES songs(id);
ALTER TABLE import_jobs ADD COLUMN existing_song_id INTEGER REFERENCES songs(id);
CREATE INDEX IF NOT EXISTS idx_import_jobs_status ON import_jobs(status, created_at);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS queue_shuffle (
  position INTEGER PRIMARY KEY,
  queue_item_id INTEGER NOT NULL REFERENCES queue_items(id) ON DELETE CASCADE
);
