INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'Radio Sausalito','','1610 AM / 1710 AM','Sausalito','CA','US','Southern Marin / Bay Area','Part 15 / Low-Power AM','Jazz / Community','Jazz / Community','Commercial-free community jazz and local information for Southern Marin. Verified direct stream.','http://quarrel.str3am.com:7090/live','gradient:blue',0,1,'https://radiosausalito.org/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('Radio Sausalito') OR stream_url='http://quarrel.str3am.com:7090/live');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'Standing Wave Radio','','1620 AM','Acra','NY','US','Upper Hudson Valley','Part 15 / Low-Power AM','Experimental / Radio Art','Experimental / Radio Art','Wave Farm transmission arts, experimental sound, and radio-art programming. Verified official stream.','https://audio.wavefarm.org/transmissionarts.mp3','gradient:violet',0,1,'https://wavefarm.org/listen' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('Standing Wave Radio') OR stream_url='https://audio.wavefarm.org/transmissionarts.mp3');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'Jacksboro Radio Network','','1610 AM','Jacksboro','TX','US','Jacksboro / North Texas','Part 15 / Low-Power AM','Country / Oldies / OTR','Classic Country / Oldies / Old-Time Radio','Local programming with classic country, early rock and roll, doo-wop, and nightly old-time radio. Verified direct stream.','https://streaming.live365.com/a18042','gradient:orange',0,1,'https://www.jacksbororadio.net/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('Jacksboro Radio Network') OR stream_url='https://streaming.live365.com/a18042');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'Liberty & Justice','','1640 AM','Shirley','MA','US','Central Massachusetts','Part 15 / Low-Power AM','Talk','Talk','Independent talk and feature programming from a Part 15 AM station in Shirley. Verified direct stream.','http://radioeast.seacoasttelephone.com:7012','gradient:red',0,1,'https://www.libertyandjustice1640.com/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('Liberty & Justice') OR stream_url='http://radioeast.seacoasttelephone.com:7012');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'Peaks Island Radio','','1700 AM','Peaks Island','ME','US','Portland / Casco Bay','Part 15 / Low-Power AM','Community / Eclectic','Community / Eclectic','Locally produced island news, public affairs, interviews, arts, and eclectic music. Verified direct stream.','https://streaming.live365.com/a55024','gradient:green',0,1,'https://peaksislandradio.com/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('Peaks Island Radio') OR stream_url='https://streaming.live365.com/a55024');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'The Valley','','1620 AM','Ligonier','PA','US','Ligonier Valley / Westmoreland County','Part 15 / Low-Power AM','Oldies / Community','Oldies / Community','Ligonier community radio with local information and music from the 1950s through the 1980s. Verified direct stream.','https://streaming.live365.com/a31025','gradient:orange',0,1,'https://ligonierradio.com/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name)=lower('The Valley') OR stream_url='https://streaming.live365.com/a31025');
INSERT INTO radio_stations(name,call_sign,frequency,city,region,country,market,station_type,format,genre,description,stream_url,artwork,favorite,enabled,website_url)
SELECT 'KHMB Radio','KHMV-LP','1710 AM / 100.9 FM','Half Moon Bay','CA','US','Coastside / Half Moon Bay','Part 15 AM Relay / LPFM','Classic Hits / Local Information','Classic Hits / Community','Community-supported Coastside music, news, entertainment, emergency, and local information. Verified direct stream.','https://streaming.live365.com/a48254','gradient:blue',0,1,'https://khmbradio.com/' WHERE NOT EXISTS(SELECT 1 FROM radio_stations WHERE lower(name) IN (lower('KHMB'),lower('KHMB Radio')) OR stream_url='https://streaming.live365.com/a48254');
