CREATE TABLE audio_output_overrides (
  name TEXT PRIMARY KEY COLLATE NOCASE,
  volume_trim INTEGER NOT NULL DEFAULT 0 CHECK(volume_trim BETWEEN -100 AND 100),
  muted INTEGER NOT NULL DEFAULT 0 CHECK(muted IN (0,1)),
  delay_ms INTEGER NOT NULL DEFAULT 0 CHECK(delay_ms BETWEEN -5000 AND 5000),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
