export type Song={id:number;title:string;artist:string;album:string;year:number;format:string;duration_ms:number;favorite:boolean;artwork?:string;track_number:number;disc_number:number;codec:string;bitrate:number;sample_rate:number;channels:number;file_size:number;original_filename:string;imported_at:string;file_path?:string;genre:string;metadata_source?:string;metadata_confidence?:number;recording_mbid?:string;release_group_mbid?:string;release_mbid?:string;metadata_locked?:boolean}
export type Storage={total_bytes:number;used_bytes:number;free_bytes:number;songs:number;albums:number;artists:number}
export type Stats={songs:number;albums:number;artists:number;stations:number;missing_artwork:number;metadata_issues:number;duplicate_files:number}
export type ImportJob={id:number;filename:string;status:'queued'|'processing'|'imported'|'duplicate'|'failed'|'cancelled';message:string;song_id?:number;existing_song_id?:number;created_at:string;updated_at:string}
export type Playlist={id:number;name:string;song_count:number;artwork?:string;updated_at:string}
export type Station={id:number;name:string;stream_url:string;genre:string;artwork?:string;favorite:boolean;call_sign:string;frequency:string;city:string;region:string;country:string;market:string;station_type:string;format:string;description:string;website_url:string;enabled:boolean}
export type PlayerState={status:string;current_song?:Song;current_radio?:Station;position_ms:number;duration_ms:number;volume:number}
export type Backup={name:string;size:number;created_at:string}
export type Page<T>={items:T[];page:number;page_size:number;total:number}
export type UploadProgress={loaded:number;total:number;percent:number}
export type FolderInfo={path:string;name:string}
export type EnrichmentStats={pending:number;processing:number;complete:number;retry:number;unmatched:number;running:boolean}
export type TorrentJob={id:number;name:string;target_folder:string;torrent_hash?:string;status:'adding'|'downloading'|'importing'|'seeding'|'expired'|'failed'|'deleted';percent:number;download_rate:number;upload_rate:number;downloaded_bytes:number;uploaded_bytes:number;total_bytes:number;peers:number;imported_count:number;total_audio:number;error?:string;completed_at?:string;seed_until?:string;created_at:string;updated_at:string}
export type AdminSession={admin:{id:number;username:string};access_expires_at?:string;refresh_expires_at?:string}
export type AudioOutput={name:string;device:string;enabled:boolean;primary:boolean;muted:boolean;exclusive:boolean;volume_trim:number;delay_ms:number;buffer_ms:number;sample_rate:number;channels?:string;format?:string;filter?:string;drift_correction_ms:number;online:boolean;error?:string;effective_volume:number;drift_ms:number}
export type UpdateRelease={current_version:string;latest_version:string;available:boolean;published_at?:string;release_url?:string;notes?:string}
export type UpdateStatus={state:string;current_version:string;target_version?:string;message?:string;updated_at:string}
let refreshing:Promise<boolean>|undefined
async function refreshOnce(){if(!refreshing)refreshing=fetch('/api/v1/auth/refresh',{method:'POST'}).then(r=>r.ok).catch(()=>false).finally(()=>{refreshing=undefined});return refreshing}
function authFailed(){window.dispatchEvent(new Event('ekkoplayer:auth-required'))}
async function req<T>(p:string,init?:RequestInit,retry=true):Promise<T>{let r=await fetch(p,{...init,credentials:'same-origin'});if(r.status===401&&retry&&p!=='/api/v1/auth/login'&&p!=='/api/v1/auth/refresh'){if(await refreshOnce())r=await fetch(p,{...init,credentials:'same-origin'});else authFailed()}if(!r.ok){if(r.status===401)authFailed();throw new Error((await r.json().catch(()=>({error:r.statusText}))).error)}return r.status===204?undefined as T:r.json()}
const json=(method:string,body:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
export const api={
 audioOutputs:()=>req<AudioOutput[]>('/api/v1/admin/audio/outputs'),audioDevices:()=>req<{devices:string[]}>('/api/v1/admin/audio/devices'),updateAudioOutput:(name:string,body:{volume_trim?:number;muted?:boolean;delay_ms?:number})=>req<AudioOutput[]>(`/api/v1/admin/audio/outputs/${encodeURIComponent(name)}`,json('PATCH',body)),
 session:()=>req<AdminSession>('/api/v1/auth/session'),login:(username:string,password:string)=>req<AdminSession>('/api/v1/auth/login',json('POST',{username,password}),false),logout:()=>req<{ok:boolean}>('/api/v1/auth/logout',{method:'POST'},false),logoutAll:()=>req<{ok:boolean}>('/api/v1/auth/logout-all',{method:'POST'}),changePassword:(current_password:string,new_password:string)=>req<{ok:boolean}>('/api/v1/auth/password',json('POST',{current_password,new_password})),
 songs:()=>req<Song[]>('/api/v1/songs'),songsPage:(page=1,pageSize=50,q='',sort='title',order='asc')=>req<Page<Song>>(`/api/v1/songs?page=${page}&page_size=${pageSize}&q=${encodeURIComponent(q)}&sort=${encodeURIComponent(sort)}&order=${order}`),songUpdate:(id:number,body:Partial<Song>)=>req<Song>(`/api/v1/songs/${id}`,json('PATCH',body)),songDelete:(id:number)=>req<void>(`/api/v1/songs/${id}`,{method:'DELETE'}),songArtwork:(id:number,file:File)=>{const b=new FormData();b.append('file',file);return req<Song>(`/api/v1/songs/${id}/artwork`,{method:'POST',body:b})},
 storage:()=>req<Storage>('/api/v1/admin/storage'),stats:()=>req<Stats>('/api/v1/admin/stats'),health:()=>req<Record<string,unknown>>('/api/v1/health'),player:()=>req<PlayerState>('/api/v1/player'),recoverPlayer:()=>req<PlayerState>('/api/v1/admin/player/recover',{method:'POST'}),restartSystem:()=>req<{status:string}>('/api/v1/admin/system/restart',{method:'POST'}),updateStatus:()=>req<UpdateStatus>('/api/v1/admin/system/update'),checkUpdate:()=>req<UpdateRelease>('/api/v1/admin/system/update/check',{method:'POST'}),applyUpdate:()=>req<UpdateStatus>('/api/v1/admin/system/update/apply',{method:'POST'}),enrichment:()=>req<EnrichmentStats>('/api/v1/admin/enrichment'),runEnrichment:()=>req<{status:string}>('/api/v1/admin/enrichment/run',{method:'POST'}),retryEnrichment:()=>req<{status:string}>('/api/v1/admin/enrichment/retry',{method:'POST'}),
 playlists:()=>req<Playlist[]>('/api/v1/playlists'),createPlaylist:(name:string)=>req<Playlist>('/api/v1/playlists',json('POST',{name})),deletePlaylist:(id:number)=>req<void>(`/api/v1/playlists/${id}`,{method:'DELETE'}),playlistArtwork:(id:number,file:File)=>{const b=new FormData();b.append('file',file);return req<Playlist[]>(`/api/v1/playlists/${id}/artwork`,{method:'POST',body:b})},resetPlaylistArtwork:(id:number)=>req<Playlist[]>(`/api/v1/playlists/${id}/artwork`,{method:'DELETE'}),playlistSongs:(id:number)=>req<Song[]>(`/api/v1/playlists/${id}/songs`),addPlaylistSong:(id:number,song_id:number)=>req<Song[]>(`/api/v1/playlists/${id}/songs`,json('POST',{song_id})),addPlaylistSongs:(id:number,song_ids:number[])=>req<Song[]>(`/api/v1/playlists/${id}/songs`,json('POST',{song_ids})),removePlaylistSong:(id:number,songID:number)=>req<Song[]>(`/api/v1/playlists/${id}/songs/${songID}`,{method:'DELETE'}),reorderPlaylist:(id:number,ids:number[])=>req<Song[]>(`/api/v1/playlists/${id}/songs`,json('PUT',{ids})),
 radio:()=>req<Station[]>('/api/v1/radio'),createRadio:(x:Omit<Station,'id'>)=>req<Station>('/api/v1/radio',json('POST',x)),updateRadio:(x:Station)=>req<Station>(`/api/v1/radio/${x.id}`,json('PUT',x)),deleteRadio:(id:number)=>req<void>(`/api/v1/radio/${id}`,{method:'DELETE'}),testRadio:(id:number)=>req<PlayerState>(`/api/v1/radio/${id}/play`,{method:'POST'}),
 folders:()=>req<FolderInfo[]>('/api/v1/admin/folders'),createFolder:(path:string)=>req<FolderInfo[]>('/api/v1/admin/folders',json('POST',{path})),moveFolder:(path:string,target:string)=>req<FolderInfo[]>('/api/v1/admin/folders',json('PATCH',{path,target})),deleteFolder:(path:string)=>req<void>(`/api/v1/admin/folders?path=${encodeURIComponent(path)}`,{method:'DELETE'}),moveSongs:(song_ids:number[],target:string)=>req<{moved:number}>('/api/v1/admin/folders/move-songs',json('POST',{song_ids,target})),renameFile:(id:number,name:string)=>req<Song>(`/api/v1/admin/files/${id}`,json('PATCH',{name})),
 imports:()=>req<ImportJob[]>('/api/v1/admin/imports'),scan:()=>req<ImportJob[]>('/api/v1/admin/imports/scan',{method:'POST'}),retry:(id:number)=>req<ImportJob>(`/api/v1/admin/imports/${id}/retry`,{method:'POST'}),cancel:(id:number)=>req<ImportJob>(`/api/v1/admin/imports/${id}`,{method:'DELETE'}),upload:(files:File[],onProgress?:(progress:UploadProgress)=>void,folder='')=>new Promise<ImportJob[]>((resolve,reject)=>{const b=new FormData();files.forEach(f=>b.append('files',f));const target=folder?`?folder=${encodeURIComponent(folder)}`:'';const xhr=new XMLHttpRequest();xhr.open('POST',`/api/v1/admin/upload${target}`);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.({loaded:e.loaded,total:e.total,percent:Math.min(100,Math.round(e.loaded/e.total*100))})};xhr.onerror=()=>reject(new Error('Upload failed. Check the connection and try again.'));xhr.onabort=()=>reject(new Error('Upload cancelled.'));xhr.onload=()=>{let body:unknown;try{body=xhr.responseText?JSON.parse(xhr.responseText):undefined}catch{body=undefined}if(xhr.status>=200&&xhr.status<300){onProgress?.({loaded:1,total:1,percent:100});resolve(body as ImportJob[])}else{const message=typeof body==='object'&&body&&'error'in body?String((body as {error:unknown}).error):xhr.statusText||`Upload failed (${xhr.status})`;reject(new Error(message))}};xhr.send(b)}),backups:()=>req<Backup[]>('/api/v1/admin/backups'),createBackup:()=>req<Backup>('/api/v1/admin/backups',{method:'POST'}),
 torrents:()=>req<TorrentJob[]>('/api/v1/admin/torrents'),addTorrent:(file:File,folder:string,onProgress?:(p:UploadProgress)=>void)=>new Promise<TorrentJob>((resolve,reject)=>{const b=new FormData();b.append('torrent',file);b.append('folder',folder);const x=new XMLHttpRequest();x.open('POST','/api/v1/admin/torrents');x.upload.onprogress=e=>e.lengthComputable&&onProgress?.({loaded:e.loaded,total:e.total,percent:Math.round(e.loaded/e.total*100)});x.onerror=()=>reject(new Error('Torrent upload failed'));x.onload=()=>{let body:any;try{body=JSON.parse(x.responseText)}catch{}if(x.status>=200&&x.status<300)resolve(body);else reject(new Error(body?.error||x.statusText))};x.send(b)}),deleteTorrent:(id:number)=>req<void>(`/api/v1/admin/torrents/${id}`,{method:'DELETE'}),extendTorrent:(id:number)=>req<TorrentJob>(`/api/v1/admin/torrents/${id}/extend`,{method:'POST'})
}
